- name: installing grafana promethues alertmanager on observer host
  hosts: observer
  roles:
    - { role: observer }
  tags:
    - observer

- name: installing node-exporters on targets host
  hosts: targets
  roles:
    - { role: targets }
  tags:
    - targets

- name: config iptables for limit targets ports just for observer
  hosts: targets
  roles:
    - { role: iptables }
  tags:
    - targets
    - iptables